miscellaneous:
  audio-cues: true

spam-prevention:
  enabled:
    chat: true
    command: true
  warn-player: true
  cooldown-ms:
    chat:
      s0: 1000
      s1: 2000
      s2: 3000
      s3: 4000
      s4: 5000
      s5: 6000
    command:
      s0: 5000
      s1: 7500
      s2: 10000
      s3: 12500
      s4: 15000
      s5: 17500

captcha:
  enabled: true
  threshold: 5
  code:
    characters: "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789"
    length: 5
  log-console: true
  whitelist: []

filter:
  enabled:
    chat: true
    sign: true
    name: true
  warn-player: true
  log:
    console: true
    local-file: true
  auto-mute:
    enabled: true
    duration:
      s0: "30m"
      s1: "1h"
      s2: "2h"
      s3: "4h"
      s4: "8h"
      s5: "24h"
  rules:
    regex: []
    terms:
      whitelist: []
      blacklist: []