miscellaneous:
  audio-cues: true

spam-prevention:
  enabled:
    chat: true
    command: true
  warn-player: true
  cooldown-ms:
    chat: [1000, 2000, 3000, 4000, 5000, 6000]
    command: [1000, 2000, 3000, 4000, 5000, 6000]
  rules-whitelist:
    command: []

captcha:
  enabled: true
  threshold: 5
  code:
    characters: "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789"
    length: 5
  log-console: true
  rules-whitelist:
    terms: []
    regex: []

filter:
  enabled:
    chat: true
    sign: true
    name: true
  warn-player: true
  log:
    console: true
    local-file: true
  auto-mute:
    enabled: true
    duration:
      - 10s
      - 2m
      - 10m
      - 30m
      - 30m
      - 30m
      - 1h
      - 1h
      - 1h
      - 2h
      - 4h
      - 8h
      - 24h
  rules:
    whitelist: []
    blacklist:
      - [\bexample filter\b, 1]
      - \banother example\b