main: io.github.aleksandarharalanov.chatguard.ChatGuard
version: 4.1.1
name: ChatGuard
author: Beezle
website: github.com/AleksandarHaralanov/ChatGuard
description: Prevents messages and usernames containing blocked terms or matching RegEx patterns, enforces mutes, stops chat and command spam, prompts captcha verification, logs actions, and applies escalating penalties.
softdepend: [Essentials]

commands:
  chatguard:
    description: All of ChatGuard's features in one command.
    usage: /chatguard
    aliases: [cg]

permissions:
  chatguard.*:
    children:
      chatguard.bypass: true
      chatguard.config: true
      chatguard.captcha: true
    description: All ChatGuard permissions.
    default: op
  chatguard.bypass:
    description: Allows player to bypass the ChatGuard protection.
    default: op
  chatguard.config:
    description: Allows player to reload and modify the ChatGuard configuration.
    default: op
  chatguard.captcha:
    description: Allows player to be notified when someone is prompted a captcha verification.
    default: op